language: node_js

node_js:
  - stable

services:
  - postgresql
  - redis-server

before_script:
  - psql -c "create database nezamedia_db_test;" -U postgres

install:
  - yarn

script:
  - yarn test
 
notification:
  - email: false

after_success:
  - yarn run coverage
